development:
  adapter: async
  url: "redis://localhost:6379/1"
  channel_prefix: backend_temperature_production

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: backend_temperature_production
